server:
  port: 8070
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mramz55555/demo-config-server-properties"
          search-paths:
            - "accounts"
            - "loans"
            - "cards"
            - "eureka-server"
            - "gateway-server"
          username: "mramz55555"
          password: "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"
          force-pull: true
          clone-on-start: true
          default-label: "master"
          timeout: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true